### ISSUE TITLE
Timing Attack - Links are invalid

### ISSUE THREAD

**Issue by MitoG** [digininja/authlab#4]
Hello,

I noticed that the links to the name lists (boys and girls) are invalid by now.
Disney seems to have bought babble or discontinued the site.

**Comment by digininja** [comment]
I've just updated the lists, but trying to rebuild the app I've hit a whole
load of problems as Go has changed the way it builds modules.

For now, use this list:

https://authlab.digi.ninja/public/wordlists/usernames.txt

**Comment by MitoG** [comment]
Great thanks.

Though I already found the original lists through webarchive.
